### ISSUE TITLE
Support tagged releases to track major versions

### ISSUE THREAD

**Issue by mtlynch** [Botspot/vdesktop#14]
It would be helpful if vdesktop supported [tagged releases](https://github.com/Botspot/vdesktop/releases) so that users could see when there were major upgrades and what the changes are between versions. It would also make it easy for users to stick to a particular version instead of relying on a branch name like [old-version](https://github.com/Botspot/vdesktop/tree/old-version).

This would allow you to get rid of the `version` file and do version checks like this:

### Check local release version

```bash
git tag | tail -n 1
```

### Check latest tagged release from Github

```bash
curl \
  --silent \
  --show-error \
  --header "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Botspot/vdesktop/releases \
  | python3 -c "import sys, json; print(json.load(sys.stdin)[0]['tag_name'])"
```

**Comment by Botspot** [comment]
OK I think I [did it right](https://github.com/Botspot/vdesktop/releases).
Would there be any way to put tags on older commits?

**Comment by mtlynch** [comment]
Yep, that's right. Github tells you to use descriptive titles, but I feel like that ends up being messy. I do it [like this](https://github.com/mtlynch/tinypilot/releases).

>Would there be any way to put tags on older commits?

Yep, you can [create a branch from an old commit and then tag a release based on that branch](https://github.community/t/create-releases-for-old-commits/872/7).

That said, I'm not sure that it's necessary. Tagged releases are a good way to communicate to users what's changed between releases, especially breaking changes. Are there legacy users who want to understand changes prior to v14?

**Comment by Botspot** [comment]
> Yep, that's right. Github tells you to use descriptive titles, but I feel like that ends up being messy. I do it [like this](https://github.com/mtlynch/tinypilot/releases).

Good point.

> That said, I'm not sure that it's necessary. Tagged releases are a good way to communicate to users what's changed between releases, especially breaking changes. Are there legacy users who want to understand changes prior to v14?

No there aren't. I was just curious if that was possible.
