### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by mtlynch** [Botspot/vdesktop#15]
Would it be possible to declare what license vdesktop and PPT are released under?

If this is an open source project, it would be helpful to specify the [open source license](https://choosealicense.com/) so that clients understand how they're allowed to use the software.

Without a license, it's [technically illegal](https://choosealicense.com/) for anyone else to run your code.

**Comment by Botspot** [comment]
Excellent suggestion. I've been meaning to add one.
OK I've added it now.

**Comment by Botspot** [comment]
I've added one to Pi-Power-Tools and [Pi-Apps](https://github.com/Botspot/pi-apps). (my latest project - an app store)
