### ISSUE TITLE
issue when updating

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/vdesktop#22]
fails to move vdesktop.old to trash.
terminal output:
```sh
pi@Twisterpi4-ultra-4gb:~/Downloads $ sudo ~/vdesktop/vdesktop ~/Downloads/2020-12-02-raspios-buster-armhf.img gui
Version 17 is available. Would you like to download it? [Y/n]
y
/home/pi/vdesktop/vdesktop: line 13: read: `-t': not a valid identifier
OK. Downloading Vdesktop.
Cloning into '/home/pi/vdesktop.new'...
remote: Enumerating objects: 183, done.
remote: Counting objects: 100% (183/183), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 381 (delta 92), reused 83 (delta 30), pack-reused 198
Receiving objects: 100% (381/381), 2.73 MiB | 685.00 KiB/s, done.
Resolving deltas: 100% (195/195), done.

New version has been downloaded. Old version is located at /home/pi/vdesktop.old
gio: file:///home/pi/vdesktop.old: Error trashing file /home/pi/vdesktop.old: No such file or directory
Copied to /home/pi/vdesktop successfully.
pi@Twisterpi4-ultra-4gb:~/Downloads $ 
```

**Comment by Botspot** [comment]
That looks to be okay. I suppose I could suppress the error. (make it hidden)

**Comment by Itai-Nelken** [comment]
why is it trying to move the old version to trash and failing than?

**Comment by Botspot** [comment]
> why is it trying to move the old version to trash and failing than?

When you update, this happens:

- New version of vdesktop is downloaded. First, we have to:
- Move the current version of vdesktop to vdesktop.old. But before we can do that, we first have to:
- Move vdesktop.old to trash.

So, if vdesktop.old doesn't exist, you will see that error.  
Make sense?

**Comment by Itai-Nelken** [comment]
yes, I just thought that it tries to move vdesktop.old to trash after reanming the old version, I didn't think about the fact that vdesktop.old will be there in all updates after the first. 
thanks for the explanaition.
