### ISSUE TITLE
apps don't open in guest OS 

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/vdesktop#23]
I booted a RPiOS 32bit image with vdesktop, and I can't open any apps other than file manager (and the run box and the shutdown/logout/reboot box). 

https://user-images.githubusercontent.com/70802936/103341373-72b25280-4a8f-11eb-9756-f97392b0e672.mp4

**Comment by Botspot** [comment]
Let's try disabling VirGL.

```
VDESKTOP_ENABLE_VIRGL=no vdesktop /path/to/your.img
```

**Comment by Itai-Nelken** [comment]
that fixed it. thanks.

**Comment by Botspot** [comment]
Interesting!

**Comment by Itai-Nelken** [comment]
I tried recompiling VirGL, still same issue.

**Comment by Itai-Nelken** [comment]
@Botspot I resized the img (and partition), and suddenly apps started opening way faster. so I enabled VirGL and apps stopped opening again.

**Comment by Botspot** [comment]
> @Botspot I resized the img (and partition), and suddenly apps started opening way faster. so I enabled VirGL and apps stopped opening again.

The only think VirGL really seems to help is Chromium v78 (outdated) and a few OpenGL programs. Besides that, it's junk.
