### ISSUE TITLE
weird icons in guest OS when booting guest from usb

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/vdesktop#24]
this happens only when booting the guest OS from usb, when booting a .img it works fine.
I started vdesktop with this command: `VDESKTOP_ENABLE_VIRGL=no vdesktop /dev/sdb gui` (virgl disabled because #23).
![weird vdesktop icons](https://user-images.githubusercontent.com/70802936/104089249-06490780-5276-11eb-8b74-aeb4512fe39c.png)

**Comment by Itai-Nelken** [comment]
after a few reboots it got normal again, I think the cause is that I ran out of space because I didn't expand the partition.

**Comment by Botspot** [comment]
I've seen this happen many times myself and don't understand how/why.

If the panel (taskbar) is misbehaving, this fixes it: `lxpanelctl restart`

**Comment by Itai-Nelken** [comment]
Thanks
