### ISSUE TITLE
Repo Bug

### ISSUE THREAD

**Issue by xpresserversllc** [Botspot/vdesktop#27]
I am trying to run GUI with vdesktop for an .img. But whenever I run "vdesktop image_file_name.img" it tries to connect ftp.br.debian.org to install virglrenderer but it always returns 404 not found error and vdesktop process exit itself. None of my apt source files are pointing to ftp.br.debian.org. I am using global mirrors for packages. I suspect ftp.br.debian.org is hard coded in vdesktop. Please fix or let me know if I am wrong

> vdesktop kali-linux-2020.4-rpi4-nexmon.img 
> Current config:
> VDESKTOP_BOOT_MODE: gui
> VDESKTOP_UMOUNT_ON_EXIT: yes
> VDESKTOP_USERNAME: pi
> VDESKTOP_PASSWORD: raspberry
> VDESKTOP_AUTO_LOGIN: yes
> VDESKTOP_MOUNTPOINT: /media/pi/vdesktop
> VDESKTOP_ENABLE_ROOTMOUNT: yes
> VDESKTOP_ENABLE_VIRGL: yes
> VDESKTOP_LOCAL_BINARIES: yes
> VDESKTOP_NSPAWN_FLAGS: 
> 
> Message from Botspot: Comments >/dev/null. Just kidding! Questions or suggestions? https://www.raspberrypi.org/forums/viewtopic.php?&t=251757
> Given kali-linux-2020.4-rpi4-nexmon.img, running in disk image mode.
> Here's the loop device for it: /dev/loop12
> 
> Current dir is /media/pi/vdesktop/etc/chromium-browser/customizations
> Current dir is /media/pi/vdesktop/etc/chromium-browser
> Made /media/pi/vdesktop/etc/chromium-browser
> Made /media/pi/vdesktop/etc/chromium-browser/customizations
> Mounted /media/pi/vdesktop/etc/chromium-browser/customizations/disable-gpu
> Mounted /media/pi/vdesktop/etc/chromium-browser/customizations/noxshm
> These directories were created to mount files:
> /media/pi/vdesktop/etc/chromium-browser
> /media/pi/vdesktop/etc/chromium-browser/customizationsEND
> Virgilrenderer server not found, but it's enabled in the config file.
> Compiling virglrenderer in 10 seconds. To cancel, press Ctrl+C before then..........
> Compiling virglrenderer now.
> --2021-02-18 02:20:22--  http://ftp.br.debian.org/debian/pool/main/libe/libepoxy/libepoxy0_1.5.4-1_armhf.deb
> Resolving ftp.br.debian.org (ftp.br.debian.org)... 200.236.31.3, 2801:82:80ff:8000::4
> Connecting to ftp.br.debian.org (ftp.br.debian.org)|200.236.31.3|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2021-02-18 02:20:23 ERROR 404: Not Found.
> 
> Failed to download libepoxy0_1.5.4-1_armhf.deb!
> Hold on...
> Unmounted /media/pi/vdesktop/etc/chromium-browser/customizations/disable-gpu
> Unmounted /media/pi/vdesktop/etc/chromium-browser/customizations/noxshm
> Removed /media/pi/vdesktop/etc/chromium-browser/customizations
> Removed /media/pi/vdesktop/etc/chromium-browser
> Cleaning up...
> Almost done...
> Done!

**Comment by Itai-Nelken** [comment]
that deb its trying to download doesn't exist, they removed it for some reason!
@Botspot here is the same file from ports.ubuntu.com: http://ports.ubuntu.com/pool/main/libe/libepoxy/libepoxy-dev_1.5.4-1_armhf.deb

**Comment by Itai-Nelken** [comment]
libepoxy0: http://ports.ubuntu.com/pool/main/libe/libepoxy/libepoxy0_1.5.4-1_armhf.deb

**Comment by Itai-Nelken** [comment]
I'll open a pr with the new links

**Comment by Itai-Nelken** [comment]
there, #28
