### ISSUE TITLE
support for different type of host OS vs guest OS- Raspian host with android guest  

### ISSUE THREAD

**Issue by FCLC** [Botspot/vdesktop#29]
Really cool project!

First off, apologies for posting without having tested in depth- will begin testing and submit a pull request will any finding once I've done so-

In the mean time any experience with running different subsets of operating systems as hosts and guests? if so, have you noted more or less success with them being of the same kernel branch (5.4.x 5.8 lts etc.?)

Woud love to hear of any experience you've had! 

-FCLC

**Comment by Botspot** [comment]
Vdesktop's functionality can be boiled down to three steps:

- Mounts the image/usb drive.
- Boots the root partition with a chroot. (Technically it uses `systemd-nspawn` for this purpose, but it's roughly equal to `chroot`.)
- Then, uses a hacky & complicated method to try to display the container's desktop. It's known to work for Kali OS, RPiOS, and TwisterOS.

Most RPi OSes (gentoo, ubuntu, other linux distros) will successfully boot to the **_console_**.  
Kali, Twister, and RPiOS go one step further and can boot to the desktop.

So to answer your question, you ought to be able to boot any linux OS to the console, using vdesktop, as long as:
- It's armhf or arm64,
- The guest OS can use the host's kernel,
- The partitions are set up the same way as stock RPiOS.

Personally I have never tried booting Android with vdesktop.

**Comment by FCLC** [comment]
Thanks for the reply, much appreciated!

My intention is to use a built of lineage OS tailored for the rpi itself. Specifically, the kernel in use is of the 5.4 branch and can be found here:

 https://github.com/lineage-rpi/android_kernel_brcm_rpi/tree/lineage-17.1

If I understand correctly, in an ideal scenario, not only would the kernels be of the same branch, but they would be exact matches correct? this includes the modules that are build in, included as modules etc.?

**Comment by Botspot** [comment]
> Thanks for the reply, much appreciated!
> 
> My intention is to use a built of lineage OS tailored for the rpi itself. Specifically, the kernel in use is of the 5.4 branch and can be found here:
> 
> https://github.com/lineage-rpi/android_kernel_brcm_rpi/tree/lineage-17.1
> 
> If I understand correctly, in an ideal scenario, not only would the kernels be of the same branch, but they would be exact matches correct? this includes the modules that are build in, included as modules etc.?

I have heard of lineage OS, but don't have in-depth knowledge of it. It may work, it may not. I'm not aware of how Android's underlying Linux system works, or if it can be `chroot`'ed into. And, there's always the chance that Lineage OS uses custom kernel modules.  
Keep me updated on your efforts. :)

**Comment by Itai-Nelken** [comment]
Android has 4 or 5 partitions if I remember correctly, so I'm pretty sure it won't work.

**Comment by FCLC** [comment]
From what I can tell from your comment and takking a brief look at the docs, it seems that if the guest requires some partition, then the host must offer them. 

So in this case, do you think the solution may be to create those partition on the host and go from there? 

as for the kernel, In principle it *should* be possible to git diff the .config of raspian and the lineage OS kernels and enable the relevant drivers that way, then bundle both into the relevant images 

The result will be a little bit of driver and kernel bloat- but no more than a few dozen megs in my estimation

**Comment by Botspot** [comment]
> From what I can tell from your comment and takking a brief look at the docs, it seems that if the guest requires some partition, then the host must offer them.
> 
> So in this case, do you think the solution may be to create those partition on the host and go from there?
> 
> as for the kernel, In principle it _should_ be possible to git diff the .config of raspian and the lineage OS kernels and enable the relevant drivers that way, then bundle both into the relevant images

No idea how possible that is.

**Comment by FCLC** [comment]
> > From what I can tell from your comment and takking a brief look at the docs, it seems that if the guest requires some partition, then the host must offer them.
> > So in this case, do you think the solution may be to create those partition on the host and go from there?
> > as for the kernel, In principle it _should_ be possible to git diff the .config of raspian and the lineage OS kernels and enable the relevant drivers that way, then bundle both into the relevant images
> 
> No idea how easy/hard that is, or if that is even possible.

Hey mate, just wanted to give you a heads up: 

Lineage OS, the guest OS I was planning on using required a 2GB+ pi4. Unfortunately only have one of the original 1GB pi4's available, so won't be able to test this- best of luck on this project, 

-FCLC
