### ISSUE TITLE
not able to boot an sd card with lineage os

### ISSUE THREAD

**Issue by Astechlab** [Botspot/vdesktop#32]
![github vdesktop sd card](https://user-images.githubusercontent.com/85675705/132700162-f83add90-1b94-45cd-a0eb-a5782eda055a.png)

**Comment by Botspot** [comment]
What kind of partition layout does /dev/sdc have?
Run this to find out:
```
df -T
```

**Comment by Itai-Nelken** [comment]
LineageOS won't work. Only OS's that use the same kernel as your host OS will work.

**Comment by Astechlab** [comment]
> What kind of partition layout does /dev/sdc have?
> Run this to find out:
> 
> ```
> df -T
> ```

![df -T](https://user-images.githubusercontent.com/85675705/132818829-57a68b1b-f1cb-436e-babe-40d8924663d2.png)

**Comment by Astechlab** [comment]
![2021-09-10_13-17](https://user-images.githubusercontent.com/85675705/132819182-de788c0d-6498-4c91-8baf-2ddc6dc89978.png)

**Comment by Botspot** [comment]
Thank you for the screenshots, I was just curious what the partition layout looked like.
But that doesn't change the fact that vdesktop can only boot operating systems that use the same kernel as your host system.
