### ISSUE TITLE
When booting old images of raspberry pi, why does it seem the new kernel is running?

### ISSUE THREAD

**Issue by mikedorin** [Botspot/vdesktop#34]
When I boot an old version of raspberry pi. Everything looks fine, but when I do a uname -a, it seems installed kernel is running, not the kernel from the old version.
I would like a VM with the old kernel running.  Is that not possible??
Thank you,
-Mike

**Comment by starbasessd** [comment]
Curiosity, do you run sudo apt update & sudo apt upgrade before checking uname?

**Comment by starbasessd** [comment]
I just did a full desktop Stretch image from 2017 (on a stripped current Buster desktop running on a Pi4b-8GB) and can confirm both report the current Buster kernel 
Linux raspi5 5.10.63-v7l+ #1457 SMP Tue Sep 28 11:26:14 BST 2021 armv7l GNU/Linux
Interesting...

**Comment by starbasessd** [comment]
I did the 2020-02-13 image, same thing.

**Comment by Botspot** [comment]
Simple answer: vdesktop is barely more than a `chroot`. It runs the guest system using the host's kernel.
