### ISSUE TITLE
Only 3GB of space is allowed to use 

### ISSUE THREAD

**Issue by cycool29** [Botspot/vdesktop#36]
I have a 32 GB SD card, but when I boot it in vdesktop (Pi Power Tool), I can only use 3 GB of it ...

Is it a normal scenario?

**Comment by Itai-Nelken** [comment]
I think you have to manually expand the filesystem. You can use PPT or gparted on the host OS.

**Comment by cycool29** [comment]
> I think you have to manually expand the filesystem. You can use PPT or GParted on the host OS.

Thanks! 
I followed [this guide](https://dev.to/rishiabee/how-to-expand-a-linux-partition-using-gparted-31c3) and I have full storage of my SD in vdesktop now! 

@Botspot I think you can add that guide in the README.
