### ISSUE TITLE
No file `rc.local` in vdesktop folder

### ISSUE THREAD

**Issue by martijintro** [Botspot/vdesktop#4]
Hi! :-)

There seems to be no file `rc.local` in the vdesktop folder i've pulled from your GIT repo.

The manual on https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=251757&p=1658781#p1658781 told me i have to add executable flag (chmod) to vdesktop/rd.local ?

Thank you for your feedback.

Best regards, Jan

**Comment by martijintro** [comment]
Maybe in relation with that issue?
-> https://github.com/Botspot/vdesktop/issues/5

**Comment by Botspot** [comment]
Sure enough. Vdesktop used to ship with a rc.local script that it would mount inside its imgs to display the user some instructions. That's no longer the case. Thank you! I've updated the instructions.

**Comment by martijintro** [comment]
Thank you too!! :-)
