### ISSUE TITLE
You did not specify what to boot

### ISSUE THREAD

**Issue by AZdave** [Botspot/vdesktop#41]
User pi has non raspberry password. 
Tried with image and still black screen of death!

$ sudo ~/vdesktop/vdesktop
You did not specify what to boot.
Available devices:
PATH         MODEL            SIZE
/dev/loop0                    9.8G
/dev/loop1                    9.8G
/dev/loop2                    9.8G
/dev/loop3                    9.8G
/dev/sdb     STORAGE_DEVICE 366.8G
/dev/mmcblk0                366.8G
find: ‘/root/Downloads’: No such file or directory

Boot a .img file: vdesktop /home/pi/2020-08-20-raspios-buster-armhf.img
Boot a usb drive: vdesktop /dev/sda
Boot a directory: vdesktop /home/pi/raspbian-stretch/

A second word specifies the boot mode: cli, cli-login, and gui.

**Comment by Botspot** [comment]
You seem to be having two problems here.

> User pi has non raspberry password.
> Tried with image and still black screen of death!

Uhh, did you try minimizing the black window to access the console to login? It should not be too hard.

> sudo ~/vdesktop/vdesktop
You did not specify what to boot.
Available devices:
PATH MODEL SIZE
/dev/loop0 9.8G
/dev/loop1 9.8G
/dev/loop2 9.8G
/dev/loop3 9.8G
/dev/sdb STORAGE_DEVICE 366.8G
/dev/mmcblk0 366.8G
find: ‘/root/Downloads’: No such file or directory
> 
> Boot a .img file: vdesktop /home/pi/2020-08-20-raspios-buster-armhf.img
Boot a usb drive: vdesktop /dev/sda
Boot a directory: vdesktop /home/pi/raspbian-stretch/
> 
> A second word specifies the boot mode: cli, cli-login, and gui.

That looks normal. Vdesktop will not boot anything if you don't tell it to boot anything.

**Comment by AZdave** [comment]
I'm trying to use Pi-Power tools and vdesktop doesn't install.
