### ISSUE TITLE
Bullseye Lite first time setup

### ISSUE THREAD

**Issue by Maki2007** [Botspot/vdesktop#45]
The new update https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/ removes the default password and user.
When I start it up for first time, it ask for login. Because there are no user in the system, in the current state, I cant login. 
How can I login?

**Comment by Botspot** [comment]
Bullseye already had some incompatibilities with vdesktop, and this new update is just another straw on the camel's back.

I haven't yet investigated what can be done. Raspberry Pi OS Legacy (Buster) does work.

**Comment by Maki2007** [comment]
Take you good time to find a good solution:-)
