### ISSUE TITLE
Proxy environment causes hang

### ISSUE THREAD

**Issue by MisterAnderson91** [Botspot/vdesktop#49]
Starting vdesktop in an environment that requires an http proxy for internet access causes hangs at startup.

The network environment causes commands such as wget to fail and get stuck forever trying to access web resources, if the proxy isn't configured (it doesn't need to be in this instance).

Simple solution would be another variable that disables checking for updates at launch. There doesn't seem to be any need to force this.

**Comment by Botspot** [comment]
Raspberry Pi OS Bullseye was changed in ways that makes it incompatible with Vdesktop in multiple fundamental ways. Since then, I've seen little point in maintaining vdesktop further.

You can disable vdesktop's internet usage by adding this line near the beginning of the `vdesktop` script:
```
wget(){ true; }
```
