### ISSUE TITLE
mount point does not exist

### ISSUE THREAD

**Issue by martijintro** [Botspot/vdesktop#5]
Screenshot here:

![Bildschirmfoto vom 2020-05-11 14-32-12](https://user-images.githubusercontent.com/42765391/81562054-81c78180-9394-11ea-84cd-e35392386f1c.png)

Thx for feedback! :-)

**Comment by martijintro** [comment]
Maybe in relation with that issue?
-> https://github.com/Botspot/vdesktop/issues/4

**Comment by Botspot** [comment]
I intended vdesktop to be run from /home/pi.
It looks like you're running vdesktop from somewhere else, and it failed to create the folder `/media/pi/vdesktop`.

Creating that folder manually might solve your problem:

    sudo mkdir /media/pi/vdesktop

^-- If you see any errors, post them.

**Comment by martijintro** [comment]
Thx!! :-)

Yes, i've done `git clone https://github.com ... ` in directory /root/TEMP

Will try it with manual creating - if it doesn't work, then i will switch to `pi` user.

**Comment by Botspot** [comment]
You could also open up the ~/vdesktop/vdesktop file and replace all mentions of "/media/pi/vdesktop" with a mountpoint of your choice.

**Comment by martijintro** [comment]
Now it seems to work with creating /media/pi/vdesktop and working as root - thx again!!

**Comment by Botspot** [comment]
You're running this on a real Raspberry Pi, right? Not Raspbian desktop for PC or Mac?

**Comment by martijintro** [comment]
Yes, that's right. Otherwise i would prefer virtualization with Win10 and VirtualBox or VMware Player and Debian instead of Raspbian as a VM.

But your product looks nice and interesting too. :-)

**Comment by martijintro** [comment]
thx, seems to work as root now...
