### ISSUE TITLE
Launch fullscreen, or launch gui from console

### ISSUE THREAD

**Issue by MisterAnderson91** [Botspot/vdesktop#50]
First up, thank you for this tool.

I am seeking to run Screenly OSE using this as the project seems to have been abandoned before Buster support was complete. Apparently at one point the development build worked on a pi 4 with Buster but it no longer successfully builds. The last premade image was based on Stretch which works fine on a pi 3 but those seem to be no longer available. It doesn't work on a pi 4. So I want to run that premade Stretch image on a pi 4 using vdesktop.

Is there a way to either launch the guest fullscreen (so there's no taskbar, no window decorations etc. from the host) or even better, just launch the guest's gui environment directly from the host's console (i.e. like raspberry pi OS lite)?

Current problems:
Launching as guest inside host's gui environment does not seem to have any ability to fullscreen the guest.
Launching from console on host fails to start X server in guest. Attempting VIRGL=yes and VIRGL=no, no difference.

**Comment by Botspot** [comment]
I would not recommend using this as a permanent solution in a production environment, but Xephyr does have a fullscreen option.

On [line 557,](https://github.com/Botspot/vdesktop/blob/f18c636e9058772cc2858c02c9cd26e0d7823542/vdesktop#L557) of the `vdesktop` script, change this:
```
Xephyr -no-host-grab -title Vdesktop -ac -screen ${screen_width}x$((screen_height-73)) -br -glamor -resizeable -dpi 96 :1 2>/dev/null &
```
To this:
```
Xephyr -no-host-grab -title Vdesktop -ac -br -glamor -dpi 96 -fullscreen :1 2>/dev/null &
```

**Comment by MisterAnderson91** [comment]
Hi, thanks very much, I appreciate the reply.
